### PR TITLE
fix issue #5331

### PR DESCRIPTION
**Pull request by rozek**
Ok, here we go...

First of all: thank you very much for this brilliant piece of software!

Here is my first contribution: the changes shown below should fix issue #5331, i.e., (color) pickers opened close to the right and bottom edges of a viewport should now be properly positioned such that they remain completely visible.

They are inspired by a [comment](https://github.com/GrapesJS/grapesjs/issues/596#issuecomment-402874045) added to issue #596 which, unfortunately, no longer works in the current version of GrapesJS.

I've cleaned up my fork of GrapesJS in order to present a clean pull request.

### CODE REVIEW

**Review by AbdullahWins — APPROVED** [review]
Good job!

**Comment by artf** [comment]
Thanks @rozek the PR looks clean and legit but I'd ask you to provide a minimal reproducible demo of the layout of the editor in order to reproduce the mentioned issue, as I'm not exactly sure how to reproduce it and so not sure if it's fixed and doesn't bring any regression.

**Comment by rozek** [comment]
Sure. However, I'm a bit busy right now - it may therefore take until the weekend before you'll get such a demo

**Comment by artf** [comment]
@rozek sure no problem

**Comment by artf** [comment]
@rozek do you have any update for the reproducible demo?

**Comment by artf** [comment]
Hey @rozek do you have any update about the demo? 🙂

**Comment by rozek** [comment]
Sorry for the silence, but I am currently quite busy with a deadline approaching.

I have to postpone the example for another week from now...

**Comment by artf** [comment]
Closing this for now as so far no one has been able to create a reproducible demo of the issue.
I'm open to reopen/review it again once a demo with a bug is provided.

**Pull request closed without merging**
